export const config = {
  id: "03",
  slug: "reconciliation",
  title: {
    ru: "Сверка депозитария",
    en: "Reconciliation",
    uk: "Звірка депозитарію",
  },
  description: {
    ru: "Синхронизация и сверка позиций, транзакций и денежных движений из депозитариев",
    en: "Synchronize and reconcile positions, transactions and cash movements from custodians",
    uk: "Синхронізація та звірка позицій, транзакцій та грошових рухів з депозитаріїв",
  },
  icon: "scale",
  collections: [
    "dataFeeds",
    "reconJobs",
    "reconBreaks",
    "reconMappings",
    "positionsSnapshots",
    "transactions",
    "dataQualityIssues",
    "syncJobs",
    "tasks",
    "documents",
    "auditEvents",
  ],
  primaryCollection: "reconBreaks",
  rbac: {
    owner: { fullAccess: true },
    admin: { fullAccess: true },
    operations: { fullAccess: true },
    cio: { fullAccess: true },
    cfo: { read: true, limitedEdit: true },
    compliance: { read: true },
    rm: { read: true },
    advisor: { read: true },
    client: {
      clientSafe: true,
      hiddenKpis: [
        "unmappedItems",
        "staleFeeds",
        "dataQualityIssues",
        "slaRisk",
      ],
      hiddenColumns: ["authStatus", "region", "externalKey", "errorDetails"],
      aggregatedView: true,
      onlySharedDocs: true,
    },
  },
  kpis: [
    {
      key: "feedHealth",
      title: { ru: "Состояние источников", en: "Feed Health" },
      format: "status",
      link: "/m/reconciliation/list?tab=feeds",
    },
    {
      key: "lastReconAt",
      title: { ru: "Последняя сверка", en: "Last Recon" },
      format: "datetime",
      link: "/m/reconciliation/list?tab=jobs",
    },
    {
      key: "openBreaks",
      title: { ru: "Открытые расхождения", en: "Open Breaks" },
      format: "number",
      link: "/m/reconciliation/list?tab=breaks&status=open",
    },
    {
      key: "criticalBreaks",
      title: { ru: "Критические", en: "Critical Breaks" },
      format: "number",
      link: "/m/reconciliation/list?tab=breaks&severity=critical",
    },
    {
      key: "unmappedItems",
      title: { ru: "Без маппинга", en: "Unmapped" },
      format: "number",
      link: "/m/reconciliation/list?tab=mappings&status=unmapped",
      clientSafeHidden: true,
    },
    {
      key: "staleFeeds",
      title: { ru: "Устаревшие источники", en: "Stale Feeds" },
      format: "number",
      link: "/m/reconciliation/list?tab=feeds&status=stale",
      clientSafeHidden: true,
    },
    {
      key: "dataQualityIssues",
      title: { ru: "Проблемы качества", en: "Data Quality" },
      format: "number",
      link: "/m/integrations/list?tab=data_quality",
      clientSafeHidden: true,
    },
    {
      key: "slaRisk",
      title: { ru: "Риск SLA", en: "SLA Risk" },
      format: "number",
      link: "/m/workflow/list?tag=recon_sla",
      clientSafeHidden: true,
    },
  ],
  breakTypes: [
    "quantity_mismatch",
    "price_mismatch",
    "missing_transaction",
    "cash_mismatch",
    "unmapped_symbol",
    "unmapped_account",
    "unmapped_entity",
  ],
  breakSeverities: ["critical", "high", "medium", "low"],
  breakStatuses: ["open", "investigating", "resolved", "ignored"],
  feedTypes: ["custodian", "bank", "advisor", "manual"],
  feedStatuses: ["ok", "stale", "error"],
  mappingStatuses: ["mapped", "unmapped", "pending"],
  jobStatuses: ["running", "completed", "failed"],
  reconScopes: ["positions", "transactions", "cash"],
};
