/**
 * PDF Placeholder Generator
 * Creates placeholder PDF content for MVP
 * In production, replace with actual PDF generation library
 */

export interface PdfSection {
  title: string;
  rowCount: number;
  columns: string[];
  preview?: string;
}

export interface PdfConfig {
  packName: string;
  packType: string;
  asOf: string;
  clientName?: string;
  clientSafe: boolean;
  sections: PdfSection[];
  disclaimers: string[];
  generatedAt: string;
  generatedBy?: string;
}

export interface PdfGenerationResult {
  fileName: string;
  content: string;
  sizeBytes: number;
  pageCount: number;
  format: 'pdf';
}

function generateCoverPage(config: PdfConfig): string {
  const lines: string[] = [
    '=' .repeat(60),
    '',
    '                    EXPORT PACK REPORT',
    '',
    '=' .repeat(60),
    '',
    `  Pack Name:        ${config.packName}`,
    `  Pack Type:        ${config.packType.toUpperCase()}`,
    `  As-of Date:       ${config.asOf}`,
    config.clientName ? `  Client:           ${config.clientName}` : '',
    `  Client-Safe:      ${config.clientSafe ? 'Yes' : 'No'}`,
    '',
    `  Generated:        ${config.generatedAt}`,
    config.generatedBy ? `  Generated By:     ${config.generatedBy}` : '',
    '',
    '-'.repeat(60),
    '',
    '  CONTENTS:',
    '',
  ].filter(Boolean);

  config.sections.forEach((section, index) => {
    lines.push(`  ${index + 1}. ${section.title} (${section.rowCount} records)`);
  });

  lines.push('');
  lines.push('-'.repeat(60));

  return lines.join('\n');
}

function generateTableOfContents(sections: PdfSection[]): string {
  const lines: string[] = [
    '',
    'TABLE OF CONTENTS',
    '='.repeat(40),
    '',
  ];

  sections.forEach((section, index) => {
    const pageNum = index + 3; // Cover + TOC = 2 pages
    lines.push(`  ${section.title}`.padEnd(35) + `Page ${pageNum}`);
  });

  lines.push('');
  lines.push('  Disclaimers'.padEnd(35) + `Page ${sections.length + 3}`);
  lines.push('');

  return lines.join('\n');
}

function generateSectionPage(section: PdfSection, pageNum: number): string {
  const lines: string[] = [
    '',
    '-'.repeat(60),
    `  Page ${pageNum}`,
    '-'.repeat(60),
    '',
    `  SECTION: ${section.title}`,
    '  ' + '='.repeat(section.title.length + 9),
    '',
    `  Total Records: ${section.rowCount}`,
    '',
    '  Columns:',
  ];

  section.columns.forEach(col => {
    lines.push(`    - ${col}`);
  });

  lines.push('');

  if (section.preview) {
    lines.push('  Data Preview:');
    lines.push('  ' + '-'.repeat(40));
    lines.push(section.preview);
    lines.push('  ' + '-'.repeat(40));
  } else {
    lines.push('  [Data available in CSV export]');
  }

  lines.push('');

  return lines.join('\n');
}

function generateDisclaimersPage(disclaimers: string[], pageNum: number): string {
  const lines: string[] = [
    '',
    '-'.repeat(60),
    `  Page ${pageNum}`,
    '-'.repeat(60),
    '',
    '  DISCLAIMERS AND NOTICES',
    '  ' + '='.repeat(25),
    '',
  ];

  disclaimers.forEach((disclaimer, index) => {
    lines.push(`  ${index + 1}. ${disclaimer}`);
    lines.push('');
  });

  lines.push('');
  lines.push('-'.repeat(60));
  lines.push('');
  lines.push('  This document was automatically generated by Wealth OS.');
  lines.push('  For questions, contact your relationship manager.');
  lines.push('');
  lines.push('  © 2024 Wealth OS. All rights reserved.');
  lines.push('');
  lines.push('='.repeat(60));
  lines.push('                         END OF REPORT');
  lines.push('='.repeat(60));

  return lines.join('\n');
}

export function generatePdfPlaceholder(config: PdfConfig): PdfGenerationResult {
  const pages: string[] = [];

  // Cover page
  pages.push(generateCoverPage(config));

  // Table of contents
  pages.push(generateTableOfContents(config.sections));

  // Section pages
  config.sections.forEach((section, index) => {
    pages.push(generateSectionPage(section, index + 3));
  });

  // Disclaimers page
  pages.push(generateDisclaimersPage(config.disclaimers, config.sections.length + 3));

  // Combine all pages
  const content = pages.join('\n\n--- PAGE BREAK ---\n\n');

  // Generate filename
  const sanitizedPack = config.packName.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
  const dateStr = config.asOf.split('T')[0];
  const fileName = `${sanitizedPack}_${dateStr}.pdf`;

  return {
    fileName,
    content,
    sizeBytes: new Blob([content]).size,
    pageCount: pages.length,
    format: 'pdf',
  };
}

export function generatePdfFilename(packName: string, asOf?: string): string {
  const sanitizedPack = packName.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
  const dateStr = asOf ? asOf.split('T')[0] : new Date().toISOString().split('T')[0];
  return `${sanitizedPack}_${dateStr}.pdf`;
}

// Default disclaimers
export const DEFAULT_DISCLAIMERS = {
  tax: 'TAX DISCLAIMER: This report is not tax advice. Consult a licensed tax professional for guidance specific to your situation.',
  audit: 'AUDIT DISCLAIMER: This audit pack is for demonstration purposes. Production use requires format controls and digital signatures.',
  confidential: 'CONFIDENTIAL: This document contains proprietary information and is intended solely for the authorized recipient.',
  accuracy: 'ACCURACY: While we strive for accuracy, this report may contain errors. Verify all data before making decisions.',
};

export function getDisclaimersForPackType(packType: string): string[] {
  const disclaimers: string[] = [DEFAULT_DISCLAIMERS.confidential, DEFAULT_DISCLAIMERS.accuracy];

  switch (packType) {
    case 'tax':
      disclaimers.unshift(DEFAULT_DISCLAIMERS.tax);
      break;
    case 'audit':
      disclaimers.unshift(DEFAULT_DISCLAIMERS.audit);
      break;
    default:
      disclaimers.unshift(DEFAULT_DISCLAIMERS.audit);
  }

  return disclaimers;
}
