import type { ModuleConfig } from '../types';

export const casesConfig: ModuleConfig = {
  id: '36',
  slug: 'cases',
  order: 36,
  icon: 'inbox',
  title: {
    ru: 'Кейсы',
    en: 'Cases',
    uk: 'Кейси',
  },
  description: {
    ru: 'Service Desk: заявки, инциденты, изменения и проблемы. Единая система кейсов для MFO operations.',
    en: 'Service Desk: requests, incidents, changes and problems. Unified case management for MFO operations.',
    uk: 'Service Desk: заявки, інциденти, зміни та проблеми. Єдина система кейсів для MFO operations.',
  },
  disclaimer: {
    ru: 'Service Desk в MVP демонстрационный. Для production требуется настройка SLA и орг процессов.',
    en: 'Service Desk is demo in MVP. Production requires SLA and org process configuration.',
    uk: 'Service Desk в MVP демонстраційний. Для production потрібно налаштування SLA та орг процесів.',
  },
  kpis: [
    {
      key: 'openInQueue',
      title: { ru: 'В очереди', en: 'Open in Queue', uk: 'В черзі' },
      format: 'number',
      status: 'warning',
      linkToList: true,
    },
    {
      key: 'myOpenCases',
      title: { ru: 'Мои открытые', en: 'My Open Cases', uk: 'Мої відкриті' },
      format: 'number',
      status: 'ok',
      linkToList: true,
    },
    {
      key: 'breachedSla',
      title: { ru: 'Нарушен SLA', en: 'Breached SLA', uk: 'Порушено SLA' },
      format: 'number',
      status: 'critical',
      linkToList: true,
    },
    {
      key: 'dueSoon24h',
      title: { ru: 'Срок 24ч', en: 'Due Soon 24h', uk: 'Термін 24г' },
      format: 'number',
      status: 'warning',
      linkToList: true,
    },
    {
      key: 'incidents7d',
      title: { ru: 'Инциденты 7д', en: 'Incidents 7d', uk: 'Інциденти 7д' },
      format: 'number',
      status: 'info',
      linkToList: true,
    },
    {
      key: 'changesPending',
      title: { ru: 'Изменения ожидают', en: 'Changes Pending', uk: 'Зміни очікують' },
      format: 'number',
      status: 'warning',
      linkToList: true,
    },
    {
      key: 'clientCasesOpen',
      title: { ru: 'Клиентские кейсы', en: 'Client Cases Open', uk: 'Клієнтські кейси' },
      format: 'number',
      status: 'ok',
      linkToList: true,
    },
    {
      key: 'caseTemplates',
      title: { ru: 'Шаблоны', en: 'Templates', uk: 'Шаблони' },
      format: 'number',
      status: 'ok',
      linkToList: true,
    },
  ],
  columns: [
    { key: 'caseNumber', header: { ru: '№ Кейса', en: 'Case #', uk: '№ Кейсу' } },
    { key: 'title', header: { ru: 'Заголовок', en: 'Title', uk: 'Заголовок' } },
    { key: 'caseType', header: { ru: 'Тип', en: 'Type', uk: 'Тип' }, type: 'badge' },
    { key: 'priority', header: { ru: 'Приоритет', en: 'Priority', uk: 'Пріоритет' }, type: 'badge' },
    { key: 'status', header: { ru: 'Статус', en: 'Status', uk: 'Статус' }, type: 'status' },
    { key: 'dueAt', header: { ru: 'SLA срок', en: 'SLA Due', uk: 'SLA термін' }, type: 'date' },
    { key: 'assignedToUserId', header: { ru: 'Исполнитель', en: 'Assignee', uk: 'Виконавець' } },
    { key: 'updatedAt', header: { ru: 'Обновлено', en: 'Updated', uk: 'Оновлено' }, type: 'date' },
  ],
  actions: [
    {
      key: 'createCase',
      label: { ru: 'Создать кейс', en: 'Create Case', uk: 'Створити кейс' },
      icon: 'plus',
      variant: 'primary',
    },
    {
      key: 'quickTriage',
      label: { ru: 'Быстрый triage', en: 'Quick Triage', uk: 'Швидкий triage' },
      icon: 'filter',
      variant: 'secondary',
    },
    {
      key: 'generateDemo',
      label: { ru: 'Demo кейсы', en: 'Generate Demo', uk: 'Demo кейси' },
      icon: 'sparkles',
      variant: 'secondary',
    },
    {
      key: 'slaReport',
      label: { ru: 'Отчет SLA', en: 'SLA Report', uk: 'Звіт SLA' },
      icon: 'chart',
      variant: 'ghost',
    },
  ],
  tabs: [
    { key: 'queue', label: { ru: 'Очередь', en: 'Queue', uk: 'Черга' } },
    { key: 'my', label: { ru: 'Мои кейсы', en: 'My Cases', uk: 'Мої кейси' } },
    { key: 'templates', label: { ru: 'Шаблоны', en: 'Templates', uk: 'Шаблони' } },
    { key: 'sla', label: { ru: 'SLA', en: 'SLA', uk: 'SLA' } },
    { key: 'reports', label: { ru: 'Отчеты', en: 'Reports', uk: 'Звіти' } },
    { key: 'audit', label: { ru: 'Аудит', en: 'Audit', uk: 'Аудит' } },
  ],
  collections: [
    'cases',
    'caseComments',
    'caseLinks',
    'caseTemplates',
    'slaPolicies',
    'caseReports',
  ],
  routes: {
    dashboard: '/m/cases',
    list: '/m/cases/list',
    caseDetail: '/m/cases/case/[id]',
    templateDetail: '/m/cases/template/[id]',
  },
};
