// Module 45: Client Portal - Configuration

import { ModuleConfig } from '../types';

export const portalConfig: ModuleConfig = {
  id: '45',
  slug: 'portal',
  order: 45,
  icon: 'portal',
  title: {
    ru: 'Портал клиента',
    en: 'Client Portal',
    uk: 'Портал клієнта',
  },
  description: {
    ru: 'Безопасный клиентский доступ к данным и сервисам',
    en: 'Secure client access to data and services',
    uk: 'Безпечний клієнтський доступ до даних та сервісів',
  },
  disclaimer: {
    ru: 'Данные предоставлены в информационных целях и не являются рекомендацией.',
    en: 'Data is provided for informational purposes and does not constitute advice.',
    uk: 'Дані надані в інформаційних цілях і не є рекомендацією.',
  },
  color: '#1a5f4a',
  enabled: true,
  collections: [
    'ptPortalUsers',
    'ptPortalViews',
    'ptPortalPreferences',
    'ptPortalRequests',
    'ptPortalThreads',
    'ptPortalMessages',
    'ptPortalDocuments',
    'ptPortalPacks',
    'ptPortalEvents',
    'ptPortalMinutes',
    'ptPortalConsents',
    'ptPortalAudit',
  ],
  kpis: [
    {
      key: 'netWorth',
      title: { ru: 'Капитал', en: 'Net Worth', uk: 'Капітал' },
      format: 'currency',
      status: 'ok',
      linkToList: true,
    },
    {
      key: 'performanceYtd',
      title: { ru: 'YTD', en: 'YTD', uk: 'YTD' },
      format: 'percent',
      status: 'ok',
      linkToList: true,
    },
    {
      key: 'cashToday',
      title: { ru: 'Денежные средства', en: 'Cash', uk: 'Грошові кошти' },
      format: 'currency',
      status: 'ok',
      linkToList: true,
    },
    {
      key: 'openRequests',
      title: { ru: 'Открытые запросы', en: 'Open Requests', uk: 'Відкриті запити' },
      format: 'number',
      status: 'ok',
      linkToList: true,
    },
    {
      key: 'newDocuments',
      title: { ru: 'Новые документы', en: 'New Documents', uk: 'Нові документи' },
      format: 'number',
      status: 'ok',
      linkToList: true,
    },
  ],
  tabs: [
    { key: 'overview', label: { ru: 'Обзор', en: 'Overview', uk: 'Огляд' } },
    { key: 'wealth', label: { ru: 'Капитал', en: 'Wealth', uk: 'Капітал' } },
    { key: 'services', label: { ru: 'Сервисы', en: 'Services', uk: 'Сервіси' } },
    { key: 'admin', label: { ru: 'Управление', en: 'Admin', uk: 'Управління' } },
  ],
  actions: [
    {
      key: 'createRequest',
      label: { ru: 'Создать запрос', en: 'Create Request', uk: 'Створити запит' },
      variant: 'primary',
      icon: 'plus',
    },
    {
      key: 'openThread',
      label: { ru: 'Написать сообщение', en: 'Send Message', uk: 'Надіслати повідомлення' },
      variant: 'secondary',
      icon: 'message',
    },
    {
      key: 'downloadPack',
      label: { ru: 'Скачать пакет', en: 'Download Pack', uk: 'Завантажити пакет' },
      variant: 'secondary',
      icon: 'download',
    },
  ],
  routes: {
    home: '/p',
    overview: '/p/overview',
    netWorth: '/p/net-worth',
    portfolios: '/p/portfolios',
    performance: '/p/performance',
    liquidity: '/p/liquidity',
    documents: '/p/documents',
    packs: '/p/packs',
    requests: '/p/requests',
    threads: '/p/threads',
    calendar: '/p/calendar',
    governance: '/p/governance',
    consents: '/p/consents',
    settings: '/p/settings',
  },
};
